/**
 * @pwngh/economy-lab
 *
 * Copyright (c) Preston Neal
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */

// Assembles the one static site from the two app builds: the docs at the root, the console under
// /console/. Run after `npm run build` in apps/docs and apps/console (or via `npm run site`); the
// result in dist-site/ is the whole deployable. Both apps use root-absolute URLs, so the site must
// be served at a domain root (GitHub Pages needs a custom domain or a *.github.io user repo).
import { createHash } from 'node:crypto';
import {
  appendFileSync,
  cpSync,
  existsSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

const DOCS = 'apps/docs/build/client';
const CONSOLE = 'apps/console/build/client';
const OUT = 'dist-site';

for (const [name, dir, marker] of [
  ['docs', DOCS, `${DOCS}/index.html`],
  ['console', CONSOLE, `${CONSOLE}/index.html`],
]) {
  if (!existsSync(marker)) {
    throw new Error(`${name} build missing (${dir}) — build both apps first.`);
  }
}

rmSync(OUT, { recursive: true, force: true });
cpSync(DOCS, OUT, { recursive: true });
cpSync(CONSOLE, `${OUT}/console`, { recursive: true });
// Without this, GitHub Pages runs the artifact through Jekyll, which drops underscore-prefixed
// files (_headers, _redirects) from the published site.
writeFileSync(`${OUT}/.nojekyll`, '');

// The console shell must exist at /console/ and the docs 404 (which also bounces console deep
// links) at the platform's 404.html.
for (const file of [
  `${OUT}/index.html`,
  `${OUT}/console/index.html`,
  `${OUT}/404.html`,
]) {
  if (!existsSync(file)) {
    throw new Error(`compose left no ${file}`);
  }
}

// The docs' `/*` CSP would govern /console/* too and block the console shell's own inline
// scripts. Emit a /console/* rule hashed from the built shell itself; the hashes change every
// build (they embed chunk names), so the rule is generated here, never hand-kept in _headers.
const headersFile = `${OUT}/_headers`;
const cspLine = readFileSync(headersFile, 'utf8')
  .split('\n')
  .find((l) => l.includes('Content-Security-Policy:'));
if (!cspLine) {
  throw new Error(
    'no Content-Security-Policy in the docs _headers to derive from',
  );
}
const consoleHashes = new Set();
// The docs 404 is served for unmatched /console/* deep links too — under this rule, not the
// docs one — so its inline scripts (the theme snippet and the console deep-link bounce) must be
// allow-listed here or the bounce dies silently and every "open txn_… in the console" link 404s.
const consolePages = readdirSync(`${OUT}/console`)
  .filter((f) => f.endsWith('.html'))
  .map((f) => join(OUT, 'console', f))
  .concat(join(OUT, '404.html'));
for (const page of consolePages) {
  const html = readFileSync(page, 'utf8');
  for (const m of html.matchAll(
    /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g,
  )) {
    if (!m[1]) continue;
    consoleHashes.add(
      `'sha256-${createHash('sha256').update(m[1], 'utf8').digest('base64')}'`,
    );
  }
}
// Same directives as the docs rule, with the console's hash set swapped into script-src.
const consoleCsp = cspLine
  .trim()
  .replace(/'sha256-[^']+'\s*/g, '')
  .replace(/script-src([^;]*)/, `script-src$1 ${[...consoleHashes].join(' ')}`)
  .replace(/\s+/g, ' ');
appendFileSync(
  headersFile,
  [
    '',
    '# Generated by scripts/compose-site.mjs: the console shell ships its own inline scripts,',
    '# so /console/* carries its own script-src hashes instead of inheriting the docs rule.',
    '/console/*',
    '  ! Content-Security-Policy',
    `  ${consoleCsp}`,
    '',
  ].join('\n'),
);

console.log(
  `composed ${OUT}/: docs at /, console at /console/ (${consoleHashes.size} console script hashes pinned)`,
);
