/**
 * @pwngh/economy-lab
 *
 * Copyright (c) Preston Neal
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */

import type { ReactNode } from 'react';

/**
 * The same call two ways: the in-process TypeScript call (the page's fence, as children) and the
 * HTTP request against `POST /submit` (`?shiki` import of the page's .sh snippet, so the shown
 * bytes are the ones runner/http.test.ts sends at the real server). The switch is two hidden
 * radio inputs and CSS — content pages ship no client React, and with JS off the TypeScript
 * panel simply stays selected. Print shows both panels.
 */
export function CallTabs({
  name,
  http,
  children,
}: {
  name: string;
  http: string;
  children: ReactNode;
}) {
  const id = `calltabs-${name}`;
  return (
    <div className="calltabs">
      <input type="radio" name={id} id={`${id}-ts`} defaultChecked />
      <input type="radio" name={id} id={`${id}-http`} />
      <div className="calltabs-bar">
        <label htmlFor={`${id}-ts`}>TypeScript</label>
        <label htmlFor={`${id}-http`}>HTTP</label>
      </div>
      <div className="calltabs-panel calltabs-ts">{children}</div>
      {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time-generated by shiki from our own files */}
      <div className="calltabs-panel calltabs-http" dangerouslySetInnerHTML={{ __html: http }} />
    </div>
  );
}
