/**
 * @pwngh/economy-lab
 *
 * Copyright (c) Preston Neal
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */

import { Runnable } from '~/components/Runnable.tsx';

import type { ReactNode } from 'react';

/**
 * A practice exercise closing a concept page: task prose, the starting code as a live workbench
 * block, then a hint and the solution behind native `<details>` — readable with JS off, same as
 * everything else here. Both code files are real: type-checked against the entry points and run
 * in CI, so the starting bug always reproduces and the answer key can't rot.
 */
export function Challenge({
  name,
  html,
  solutionHtml,
  hint,
  explain,
  children,
}: {
  name: string;
  html: string;
  solutionHtml: string;
  hint: string;
  explain: string;
  children: ReactNode;
}) {
  return (
    <section className="challenge">
      <div className="challenge-task">{children}</div>
      <Runnable name={name} html={html} />
      <details className="challenge-fold">
        <summary>Hint</summary>
        <p>{hint}</p>
      </details>
      <details className="challenge-fold">
        <summary>Solution</summary>
        <p>{explain}</p>
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time-generated by shiki from our own files */}
        <div className="challenge-code" dangerouslySetInnerHTML={{ __html: solutionHtml }} />
      </details>
    </section>
  );
}
