/**
 * @pwngh/economy-lab
 *
 * Copyright (c) Preston Neal
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.md file in the root directory of this source tree.
 *
 * @license MIT
 */

/**
 * A runnable snippet block. `html` is the snippet file itself, Shiki-highlighted at build time
 * (`?shiki` import), so what the reader sees is byte-for-byte what runs — the file is
 * type-checked and executed against the real engine in CI. The code is an editor: click into it
 * and type (loader.js swaps in the workbench at the caret). Everything heavy loads on intent —
 * the engine on the first run, the sandbox and transpiler on the first edited run. With JS off,
 * it is exactly a highlighted code block.
 */
export function Runnable({ name, html }: { name: string; html: string }) {
  return (
    <figure className="runnable" data-snippet={name}>
      {/* biome-ignore lint/security/noDangerouslySetInnerHtml: build-time-generated by shiki from our own files */}
      <div className="runnable-code" dangerouslySetInnerHTML={{ __html: html }} />
      <div className="runnable-bar" data-bar hidden>
        <span className="runnable-note" data-note />
        <button type="button" className="runnable-reset" data-reset-code hidden>
          Reset code
        </button>
        {/* Never shown here: the output footer's "reset economy" delegates to it. */}
        <button type="button" className="runnable-reset" data-reset-economy hidden>
          Reset economy
        </button>
        <button type="button" className="runnable-run" data-run>
          Run
        </button>
      </div>
      <output className="runnable-out" data-out hidden />
      <script type="module" src="/runner/loader.js" />
    </figure>
  );
}
